universe = docker
docker_image = requiem98/geolocdock:v01
executable = /bin/python3
arguments = /home/amedeo_ranaldi/cell_division_SNAIL_partitioning/cell_noise_MAIN.py 100 500 1500 10 0 0 15 unito 0
output = /home/amedeo_ranaldi/SNAIL_15/CondorLogs/out.$(ClusterId).$(ProcId)
error = /home/amedeo_ranaldi/SNAIL_15/CondorLogs/err.$(ClusterId).$(ProcId)
log = /home/amedeo_ranaldi/SNAIL_15/CondorLogs/log.$(ClusterId).$(ProcId)
request_cpus = 1
request_gpus = 0
request_memory = 32G
request_disk = 50G
+MountData1=FALSE
+MountData2=FALSE
+MountHomes=TRUE
queue 1

